# Generated by Django 4.2.4 on 2023-09-07 10:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_siteinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=100)),
                ('Fulladdress', models.CharField(max_length=300)),
                ('phone', models.CharField(max_length=15)),
                ('time', models.CharField(max_length=150)),
                ('email', models.EmailField(max_length=300)),
                ('words', models.CharField(max_length=150)),
            ],
        ),
    ]
