# Generated by Django 4.2.4 on 2023-09-11 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_contact'),
    ]

    operations = [
        migrations.RenameField(
            model_name='contact',
            old_name='address',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='Fulladdress',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='phone',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='time',
        ),
        migrations.RemoveField(
            model_name='contact',
            name='words',
        ),
        migrations.AddField(
            model_name='contact',
            name='message',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='contact',
            name='subject',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
