# Generated by Django 4.2.4 on 2023-09-11 17:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0006_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
    ]
