# Generated by Django 4.2.4 on 2023-09-13 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='FrontPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('greetings', models.CharField(max_length=30)),
                ('fullname', models.CharField(max_length=20)),
                ('shortintro', models.CharField(max_length=100)),
                ('visitsite', models.TextField()),
                ('image', models.ImageField(upload_to='media')),
                ('infoheading', models.CharField(max_length=20)),
            ],
        ),
    ]
