# Generated by Django 4.2.4 on 2023-09-17 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0010_frontpage'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='Personalcv',
            field=models.CharField(default=1, max_length=100),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='frontpage',
            name='infodetail',
            field=models.TextField(default=1),
            preserve_default=False,
        ),
    ]
