# Generated by Django 4.2.4 on 2023-09-17 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0011_frontpage_personalcv_frontpage_infodetail'),
    ]

    operations = [
        migrations.AddField(
            model_name='frontpage',
            name='secondimage',
            field=models.ImageField(default=1, upload_to='media'),
            preserve_default=False,
        ),
    ]
